CREATE TABLE STUDENT(
    학생명 VARCHAR(20),
    국어 INT,
    영어 INT
);

INSERT INTO STUDENT VALUES ('유리', 100, 80);
INSERT INTO STUDENT VALUES ('철수', 50, 70);
INSERT INTO STUDENT VALUES ('영식', 80, 90);
INSERT INTO STUDENT VALUES ('미선', 70, 100);

-- 집계함수
SELECT COUNT(*)
FROM STUDENT
WHERE 국어 >= 80;

SELECT SUM(국어), AVG(영어)
FROM STUDENT;

SELECT MAX(국어), MIN(국어)
FROM STUDENT;

SELECT STDDEV(국어), VARIANCE(국어)
FROM STUDENT;

-- 윈도함수
SELECT EMP_NAME, SALARY, 
    RANK() OVER (ORDER BY SALARY DESC) A,
    DENSE_RANK() OVER (ORDER BY SALARY DESC) B,
    ROW_NUMBER() OVER (ORDER BY SALARY DESC) C
FROM EMP2;
