-- 서브쿼리
-- sql문 안에 포함된 또 다른 sql문

SELECT MAX(가격) AS 가격
FROM 도서가격 A, (SELECT 책번호 FROM 도서 WHERE 책명='자료구조') B
WHERE A.책번호 = B.책번호;

SELECT MAX(가격) AS 가격
FROM 도서가격
WHERE 책번호 = (SELECT 책번호 FROM 도서 WHERE 책명='자료구조');

-- 집합연산자
CREATE TABLE EMP(
    EMPNO INT,
    ENAME VARCHAR(20),
    JOB VARCHAR(20),
    SAL INT
);

INSERT INTO EMP VALUES (1001, '홍길동', '대리', 1000);
INSERT INTO EMP VALUES (1002, '임꺽정', '과장', 1500);
INSERT INTO EMP VALUES (1003, '장길산', '차장', 2000);
INSERT INTO EMP VALUES (1004, '강은미', '부장', 2500);

SELECT ENAME
FROM EMP
WHERE SAL <= 2000
UNION
SELECT ENAME
FROM EMP
WHERE SAL >= 1500;

SELECT ENAME
FROM EMP
WHERE SAL <= 2000
UNION ALL
SELECT ENAME
FROM EMP
WHERE SAL >= 1500;

SELECT ENAME
FROM EMP
WHERE SAL <= 2000
INTERSECT
SELECT ENAME
FROM EMP
WHERE SAL >= 1500;

SELECT ENAME
FROM EMP
WHERE SAL <= 2000
MINUS
SELECT ENAME
FROM EMP
WHERE SAL >= 1500;
